### ISSUE TITLE
Need LICENSE

### ISSUE THREAD

**Issue by avamk** [shivanju/pyxel-games#1]
Thanks for creating such a great game for pyxel!! And thanks for the invitation for improvements. :smile:

However, there is currently no LICENSE attached to this project and hence it is proprietary. Can you please attach a license such as the GNU GPLv3+? Thanks!!

**Comment by shivanju** [comment]
Hi. Thanks for giving some time for feedback. I am glad you liked it. I'll add more games in near future. Finally, I've added the MIT license for this repository.
